#!/bin/bash

rm experiment2/wrong/picture_*
rm experiment2/all/picture_*
python3 generate_human_test.py
rm experiment2.zip
zip -r experiment2.zip experiment2
rm ../www_docs/experiment2.zip
cp experiment2.zip ../www_docs
